# Generated by Django 5.0 on 2023-12-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='brand',
            new_name='marque',
        ),
        migrations.RemoveField(
            model_name='car',
            name='displacement',
        ),
    ]
